version: 2
updates:
  # Enable version updates for npm (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  # Enable version updates for npm (api)
  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  # Enable version updates for npm (database)
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  # Enable version updates for npm (discord-bot)
  - package-ecosystem: "npm"
    directory: "/packages/discord-bot"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  # Enable version updates for npm (shared)
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  # Enable version updates for npm (web)
  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
