/**
 * Prisma enum types
 * These enums are now generated by Prisma and exported from @prisma/client
 * This file kept for backwards compatibility but exports nothing to avoid duplicates
 */

export {};
